// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post_bookmarks.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPostBookmark = `-- name: CreatePostBookmark :one
with inserted_bookmark as (
    insert into post_bookmarks (id, created_at, updated_at, user_id, post_id)
    values ($1, $2, $3, $4, $5)
    returning id, created_at, updated_at, user_id, post_id
)
select inserted_bookmark.id, inserted_bookmark.created_at, inserted_bookmark.updated_at, inserted_bookmark.user_id, inserted_bookmark.post_id,
       posts.title as post_title,
       posts.url as post_url
from inserted_bookmark
inner join posts on inserted_bookmark.post_id = posts.id
`

type CreatePostBookmarkParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	PostID    uuid.UUID
}

type CreatePostBookmarkRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	PostID    uuid.UUID
	PostTitle string
	PostUrl   string
}

func (q *Queries) CreatePostBookmark(ctx context.Context, arg CreatePostBookmarkParams) (CreatePostBookmarkRow, error) {
	row := q.db.QueryRowContext(ctx, createPostBookmark,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.PostID,
	)
	var i CreatePostBookmarkRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.PostID,
		&i.PostTitle,
		&i.PostUrl,
	)
	return i, err
}

const deletePostBookmark = `-- name: DeletePostBookmark :exec
delete from post_bookmarks
where user_id = $1 and post_id = $2
`

type DeletePostBookmarkParams struct {
	UserID uuid.UUID
	PostID uuid.UUID
}

func (q *Queries) DeletePostBookmark(ctx context.Context, arg DeletePostBookmarkParams) error {
	_, err := q.db.ExecContext(ctx, deletePostBookmark, arg.UserID, arg.PostID)
	return err
}

const getBookmarkedPostsForUser = `-- name: GetBookmarkedPostsForUser :many
select posts.id, posts.created_at, posts.updated_at, posts.title, posts.url, posts.description, posts.published_at, posts.feed_id
from post_bookmarks
inner join posts on post_bookmarks.post_id = posts.id
where post_bookmarks.user_id = $1
order by post_bookmarks.created_at desc
`

func (q *Queries) GetBookmarkedPostsForUser(ctx context.Context, userID uuid.UUID) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getBookmarkedPostsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
