// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post_likes.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPostLike = `-- name: CreatePostLike :one
with inserted_like as (
    insert into post_likes (id, created_at, updated_at, user_id, post_id)
    values ($1, $2, $3, $4, $5)
    returning id, created_at, updated_at, user_id, post_id
)
select inserted_like.id, inserted_like.created_at, inserted_like.updated_at, inserted_like.user_id, inserted_like.post_id,
       posts.title as post_title,
       posts.url as post_url
from inserted_like
inner join posts on inserted_like.post_id = posts.id
`

type CreatePostLikeParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	PostID    uuid.UUID
}

type CreatePostLikeRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	PostID    uuid.UUID
	PostTitle string
	PostUrl   string
}

func (q *Queries) CreatePostLike(ctx context.Context, arg CreatePostLikeParams) (CreatePostLikeRow, error) {
	row := q.db.QueryRowContext(ctx, createPostLike,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.PostID,
	)
	var i CreatePostLikeRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.PostID,
		&i.PostTitle,
		&i.PostUrl,
	)
	return i, err
}

const deletePostLike = `-- name: DeletePostLike :exec
delete from post_likes
where user_id = $1 and post_id = $2
`

type DeletePostLikeParams struct {
	UserID uuid.UUID
	PostID uuid.UUID
}

func (q *Queries) DeletePostLike(ctx context.Context, arg DeletePostLikeParams) error {
	_, err := q.db.ExecContext(ctx, deletePostLike, arg.UserID, arg.PostID)
	return err
}

const getLikedPostsForUser = `-- name: GetLikedPostsForUser :many
select posts.id, posts.created_at, posts.updated_at, posts.title, posts.url, posts.description, posts.published_at, posts.feed_id
from post_likes
inner join posts on post_likes.post_id = posts.id
where post_likes.user_id = $1
order by post_likes.created_at desc
`

func (q *Queries) GetLikedPostsForUser(ctx context.Context, userID uuid.UUID) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getLikedPostsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
