// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
insert into posts(id, created_at, updated_at, title, url, description, published_at, feed_id)
values ($1, $2, $3, $4, $5, $6, $7, $8)
returning id, created_at, updated_at, title, url, description, published_at, feed_id
`

type CreatePostParams struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Url         string
	Description sql.NullString
	PublishedAt sql.NullTime
	FeedID      uuid.UUID
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.PublishedAt,
		arg.FeedID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.PublishedAt,
		&i.FeedID,
	)
	return i, err
}

const getPostByURL = `-- name: GetPostByURL :one
select id, created_at, updated_at, title, url, description, published_at, feed_id from posts where url = $1
`

func (q *Queries) GetPostByURL(ctx context.Context, url string) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostByURL, url)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.PublishedAt,
		&i.FeedID,
	)
	return i, err
}

const getPostsForUser = `-- name: GetPostsForUser :many
select posts.id, posts.created_at, posts.updated_at, posts.title, posts.url, posts.description, posts.published_at, posts.feed_id
from posts
inner join feed_follows on posts.feed_id = feed_follows.feed_id
where feed_follows.user_id = $1
order by posts.published_at desc nulls last
limit $2
`

type GetPostsForUserParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) GetPostsForUser(ctx context.Context, arg GetPostsForUserParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsForUserByPublishedAtAsc = `-- name: GetPostsForUserByPublishedAtAsc :many
select posts.id, posts.created_at, posts.updated_at, posts.title, posts.url, posts.description, posts.published_at, posts.feed_id
from posts
inner join feed_follows on posts.feed_id = feed_follows.feed_id
inner join feeds on feed_follows.feed_id = feeds.id
where feed_follows.user_id = $1
and ($4::text is null or feeds.name = $4)
order by posts.published_at asc nulls last
limit $2
offset $3
`

type GetPostsForUserByPublishedAtAscParams struct {
	UserID   uuid.UUID
	Limit    int32
	Offset   int32
	FeedName sql.NullString
}

func (q *Queries) GetPostsForUserByPublishedAtAsc(ctx context.Context, arg GetPostsForUserByPublishedAtAscParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForUserByPublishedAtAsc,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.FeedName,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsForUserByPublishedAtDesc = `-- name: GetPostsForUserByPublishedAtDesc :many
select posts.id, posts.created_at, posts.updated_at, posts.title, posts.url, posts.description, posts.published_at, posts.feed_id
from posts
inner join feed_follows on posts.feed_id = feed_follows.feed_id
inner join feeds on feed_follows.feed_id = feeds.id
where feed_follows.user_id = $1
and ($4::text is null or feeds.name = $4)
order by posts.published_at desc nulls last
limit $2
offset $3
`

type GetPostsForUserByPublishedAtDescParams struct {
	UserID   uuid.UUID
	Limit    int32
	Offset   int32
	FeedName sql.NullString
}

func (q *Queries) GetPostsForUserByPublishedAtDesc(ctx context.Context, arg GetPostsForUserByPublishedAtDescParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForUserByPublishedAtDesc,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.FeedName,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsForUserByTitleAsc = `-- name: GetPostsForUserByTitleAsc :many
select posts.id, posts.created_at, posts.updated_at, posts.title, posts.url, posts.description, posts.published_at, posts.feed_id
from posts
inner join feed_follows on posts.feed_id = feed_follows.feed_id
inner join feeds on feed_follows.feed_id = feeds.id
where feed_follows.user_id = $1
and ($4::text is null or feeds.name = $4)
order by posts.title asc
limit $2
offset $3
`

type GetPostsForUserByTitleAscParams struct {
	UserID   uuid.UUID
	Limit    int32
	Offset   int32
	FeedName sql.NullString
}

func (q *Queries) GetPostsForUserByTitleAsc(ctx context.Context, arg GetPostsForUserByTitleAscParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForUserByTitleAsc,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.FeedName,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsForUserByTitleDesc = `-- name: GetPostsForUserByTitleDesc :many
select posts.id, posts.created_at, posts.updated_at, posts.title, posts.url, posts.description, posts.published_at, posts.feed_id
from posts
inner join feed_follows on posts.feed_id = feed_follows.feed_id
inner join feeds on feed_follows.feed_id = feeds.id
where feed_follows.user_id = $1
and ($4::text is null or feeds.name = $4)
order by posts.title desc
limit $2
offset $3
`

type GetPostsForUserByTitleDescParams struct {
	UserID   uuid.UUID
	Limit    int32
	Offset   int32
	FeedName sql.NullString
}

func (q *Queries) GetPostsForUserByTitleDesc(ctx context.Context, arg GetPostsForUserByTitleDescParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForUserByTitleDesc,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.FeedName,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPostsForUser = `-- name: SearchPostsForUser :many
select posts.id, posts.created_at, posts.updated_at, posts.title, posts.url, posts.description, posts.published_at, posts.feed_id
from posts
inner join feed_follows on posts.feed_id = feed_follows.feed_id
where feed_follows.user_id = $1
and similarity(posts.title, $2) > 0.1
order by similarity(posts.title, $2) desc
limit $3
`

type SearchPostsForUserParams struct {
	UserID     uuid.UUID
	Similarity string
	Limit      int32
}

func (q *Queries) SearchPostsForUser(ctx context.Context, arg SearchPostsForUserParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, searchPostsForUser, arg.UserID, arg.Similarity, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
